/* 自动生成，请勿手改。来源：tools/gen-seed.js */
module.exports = [
  {
    "id": "p_f01",
    "name": "林晚晴",
    "gender": "f",
    "age": 27,
    "job": "小学老师",
    "avatar": "teacher",
    "look": "笑起来眼睛弯弯的",
    "trait": "温柔",
    "condition": "本地有房",
    "hobby": "看书",
    "place": "亲戚介绍的",
    "personalityId": "emo",
    "looks": 74,
    "family": 62,
    "first": 6,
    "weight": 12,
    "tagline": "带完一届学生，终于有空谈恋爱了"
  },
  {
    "id": "p_f02",
    "name": "苏念",
    "gender": "f",
    "age": 25,
    "job": "三甲医院护士",
    "avatar": "nurse",
    "look": "皮肤很白，不太爱说话",
    "trait": "顾家",
    "condition": "外地打拼",
    "hobby": "瑜伽",
    "place": "同事牵线搭桥的",
    "personalityId": "family",
    "looks": 71,
    "family": 38,
    "first": 2,
    "weight": 11,
    "tagline": "刚下夜班，眼圈有点青"
  },
  {
    "id": "p_f03",
    "name": "陈嘉宜",
    "gender": "f",
    "age": 29,
    "job": "银行柜员",
    "avatar": "accountant",
    "look": "戴一副细框眼镜，很斯文",
    "trait": "务实",
    "condition": "有房贷",
    "hobby": "打游戏",
    "place": "婚恋 App 上划到的",
    "personalityId": "money",
    "looks": 68,
    "family": 55,
    "first": 0,
    "weight": 11,
    "tagline": "白天数别人的钱，晚上数自己的"
  },
  {
    "id": "p_f04",
    "name": "江雨欣",
    "gender": "f",
    "age": 26,
    "job": "互联网产品经理",
    "avatar": "programmer",
    "look": "短发利落，说话时手势很多",
    "trait": "事业心强",
    "condition": "外地打拼",
    "hobby": "跑步",
    "place": "同学会上重逢的",
    "personalityId": "career",
    "looks": 76,
    "family": 47,
    "first": 4,
    "weight": 12,
    "tagline": "需求评审比相亲还难"
  },
  {
    "id": "p_f05",
    "name": "沈书瑶",
    "gender": "f",
    "age": 24,
    "job": "在读博士",
    "avatar": "anime",
    "look": "长相普通，但越看越耐看",
    "trait": "敏感",
    "condition": "家境普通",
    "hobby": "逛展",
    "place": "兴趣小组里聊起来的",
    "personalityId": "emo",
    "looks": 63,
    "family": 41,
    "first": -2,
    "weight": 10,
    "tagline": "实验室的灯，比家里的亮"
  },
  {
    "id": "p_f06",
    "name": "顾清越",
    "gender": "f",
    "age": 30,
    "job": "设计师",
    "avatar": "artsy",
    "look": "穿着很讲究，看得出花了心思",
    "trait": "强势",
    "condition": "家境优渥",
    "hobby": "摄影",
    "place": "朋友聚会上认识的",
    "personalityId": "char",
    "looks": 79,
    "family": 78,
    "first": 1,
    "weight": 11,
    "tagline": "审美是一道过不去的坎"
  },
  {
    "id": "p_f07",
    "name": "何知意",
    "gender": "f",
    "age": 28,
    "job": "公务员",
    "avatar": "civil-servant",
    "look": "话不多，眼神很稳",
    "trait": "顾家",
    "condition": "本地有房",
    "hobby": "爬山",
    "place": "父母在公园相亲角「淘」来的",
    "personalityId": "family",
    "looks": 70,
    "family": 66,
    "first": 3,
    "weight": 11,
    "tagline": "稳定是最大的优点，也是全部"
  },
  {
    "id": "p_f08",
    "name": "温言",
    "gender": "f",
    "age": 27,
    "job": "中学教师",
    "avatar": "teacher",
    "look": "有点像你高中时喜欢过的那个人",
    "trait": "直球",
    "condition": "本地有房",
    "hobby": "看电影",
    "place": "亲戚介绍的",
    "personalityId": "char",
    "looks": 75,
    "family": 60,
    "first": 5,
    "weight": 12,
    "tagline": "会习惯性纠正你的用词"
  },
  {
    "id": "p_f09",
    "name": "白露",
    "gender": "f",
    "age": 26,
    "job": "广告公司文案",
    "avatar": "artsy",
    "look": "个子很高，站在人群里很好找",
    "trait": "浪漫",
    "condition": "家境普通",
    "hobby": "看livehouse演出",
    "place": "朋友聚会上认识的",
    "personalityId": "casual",
    "looks": 77,
    "family": 44,
    "first": 0,
    "weight": 11,
    "tagline": "文案写得漂亮，日子过得潦草"
  },
  {
    "id": "p_f10",
    "name": "夏知许",
    "gender": "f",
    "age": 31,
    "job": "销售经理",
    "avatar": "wealthy",
    "look": "妆容精致，气场很足",
    "trait": "强势",
    "condition": "家境优渥",
    "hobby": "自驾游",
    "place": "婚恋 App 上划到的",
    "personalityId": "money",
    "looks": 82,
    "family": 84,
    "first": -3,
    "weight": 12,
    "tagline": "太会说话了，你有时分不清真假"
  },
  {
    "id": "p_f11",
    "name": "叶轻舟",
    "gender": "f",
    "age": 28,
    "job": "开咖啡馆的",
    "avatar": "artsy",
    "look": "身上有咖啡味，和一点疲惫",
    "trait": "温柔",
    "condition": "单亲家庭",
    "hobby": "咖啡",
    "place": "兴趣小组里聊起来的",
    "personalityId": "family",
    "looks": 73,
    "family": 39,
    "first": 2,
    "weight": 10,
    "tagline": "把店开成了家，把家过成了店"
  },
  {
    "id": "p_f12",
    "name": "罗一帆",
    "gender": "f",
    "age": 32,
    "job": "急诊科医生",
    "avatar": "doctor",
    "look": "眼神很稳，像见惯了大事",
    "trait": "顾家",
    "condition": "本地有房",
    "hobby": "做饭",
    "place": "同事牵线搭桥的",
    "personalityId": "char",
    "looks": 69,
    "family": 64,
    "first": 1,
    "weight": 10,
    "tagline": "永远在抢救，永远在熬夜"
  },
  {
    "id": "p_m01",
    "name": "陈亦舟",
    "gender": "m",
    "age": 29,
    "job": "互联网产品经理",
    "avatar": "programmer",
    "look": "个子很高，站在人群里很好找",
    "trait": "事业心强",
    "condition": "外地打拼",
    "hobby": "跑步",
    "place": "同学会上重逢的",
    "personalityId": "career",
    "looks": 73,
    "family": 45,
    "first": 3,
    "weight": 12,
    "tagline": "会画原型图，也画人生规划"
  },
  {
    "id": "p_m02",
    "name": "顾停云",
    "gender": "m",
    "age": 31,
    "job": "公务员",
    "avatar": "civil-servant",
    "look": "说话滴水不漏，像一份标准答案",
    "trait": "务实",
    "condition": "本地有房",
    "hobby": "打羽毛球",
    "place": "父母在公园相亲角「淘」来的",
    "personalityId": "family",
    "looks": 68,
    "family": 63,
    "first": 2,
    "weight": 11,
    "tagline": "稳定，是相亲市场里的硬通货"
  },
  {
    "id": "p_m03",
    "name": "周牧野",
    "gender": "m",
    "age": 27,
    "job": "健身教练",
    "avatar": "coach",
    "look": "肩膀很宽，走路带风",
    "trait": "直球",
    "condition": "外地打拼",
    "hobby": "爬山",
    "place": "朋友聚会上认识的",
    "personalityId": "char",
    "looks": 81,
    "family": 40,
    "first": 6,
    "weight": 11,
    "tagline": "朋友圈全是自律语录"
  },
  {
    "id": "p_m04",
    "name": "沈屿",
    "gender": "m",
    "age": 30,
    "job": "自由摄影师",
    "avatar": "photographer",
    "look": "话不多，但眼睛很亮",
    "trait": "浪漫",
    "condition": "家境普通",
    "hobby": "摄影",
    "place": "兴趣小组里聊起来的",
    "personalityId": "casual",
    "looks": 72,
    "family": 42,
    "first": 1,
    "weight": 11,
    "tagline": "收入不稳定，但眼里有光"
  },
  {
    "id": "p_m05",
    "name": "江淮",
    "gender": "m",
    "age": 33,
    "job": "销售经理",
    "avatar": "wealthy",
    "look": "西装笔挺，笑起来很熟练",
    "trait": "强势",
    "condition": "家境优渥",
    "hobby": "自驾游",
    "place": "婚恋 App 上划到的",
    "personalityId": "money",
    "looks": 74,
    "family": 86,
    "first": -3,
    "weight": 12,
    "tagline": "太会说话了，你分不清哪句是真的"
  },
  {
    "id": "p_m06",
    "name": "陆则",
    "gender": "m",
    "age": 28,
    "job": "急诊科医生",
    "avatar": "doctor",
    "look": "眼下有淡青，站姿却很稳",
    "trait": "顾家",
    "condition": "本地有房",
    "hobby": "做饭",
    "place": "同事牵线搭桥的",
    "personalityId": "family",
    "looks": 70,
    "family": 61,
    "first": 2,
    "weight": 10,
    "tagline": "值班表比恋爱日历还满"
  },
  {
    "id": "p_m07",
    "name": "温既白",
    "gender": "m",
    "age": 26,
    "job": "广告公司文案",
    "avatar": "artsy",
    "look": "笑起来眼睛弯弯的",
    "trait": "敏感",
    "condition": "家境普通",
    "hobby": "看电影",
    "place": "同学会上重逢的",
    "personalityId": "emo",
    "looks": 71,
    "family": 43,
    "first": 0,
    "weight": 10,
    "tagline": "嘴很毒，观察力惊人"
  },
  {
    "id": "p_m08",
    "name": "秦朗",
    "gender": "m",
    "age": 32,
    "job": "餐厅主厨",
    "avatar": "chef",
    "look": "手臂上有烫疤，说话很直",
    "trait": "爱玩",
    "condition": "单亲家庭",
    "hobby": "做饭",
    "place": "亲戚介绍的",
    "personalityId": "char",
    "looks": 66,
    "family": 44,
    "first": -1,
    "weight": 9,
    "tagline": "火候拿捏得很好，人生搞得很糟"
  },
  {
    "id": "p_m09",
    "name": "韩序",
    "gender": "m",
    "age": 27,
    "job": "程序员",
    "avatar": "programmer",
    "look": "戴一副细框眼镜，很斯文",
    "trait": "话少",
    "condition": "有房贷",
    "hobby": "打游戏",
    "place": "婚恋 App 上划到的",
    "personalityId": "money",
    "looks": 69,
    "family": 52,
    "first": 0,
    "weight": 12,
    "tagline": "话不多，说到技术会突然兴奋"
  },
  {
    "id": "p_m10",
    "name": "白砚",
    "gender": "m",
    "age": 35,
    "job": "创业公司 CEO",
    "avatar": "startup-fail",
    "look": "衬衫皱了，领带却系得很正",
    "trait": "事业心强",
    "condition": "外地打拼",
    "hobby": "咖啡",
    "place": "朋友聚会上认识的",
    "personalityId": "career",
    "looks": 72,
    "family": 70,
    "first": -2,
    "weight": 10,
    "tagline": "张口就是估值和赛道"
  },
  {
    "id": "p_m11",
    "name": "邵一鸣",
    "gender": "m",
    "age": 29,
    "job": "设计师",
    "avatar": "artsy",
    "look": "穿着很讲究，看得出花了心思",
    "trait": "强势",
    "condition": "家境优渥",
    "hobby": "逛展",
    "place": "兴趣小组里聊起来的",
    "personalityId": "char",
    "looks": 76,
    "family": 76,
    "first": 0,
    "weight": 11,
    "tagline": "审美很好，也很挑剔"
  },
  {
    "id": "p_m12",
    "name": "贺远",
    "gender": "m",
    "age": 34,
    "job": "国企老员工",
    "avatar": "older-single",
    "look": "不太说话，保温杯不离手",
    "trait": "顾家",
    "condition": "本地有房",
    "hobby": "养猫",
    "place": "父母在公园相亲角「淘」来的",
    "personalityId": "family",
    "looks": 61,
    "family": 58,
    "first": 1,
    "weight": 9,
    "tagline": "波澜不惊，等着退休"
  }
];
